### ISSUE TITLE
Just need help on how you saved weights of nn4.small2.v1 in CSV

### ISSUE THREAD

**Issue by jadhavsaurabh** [krasserm/face-recognition#16]
As I visited openface website and saw the pre-trained model it was in 't7' extension which is for 'Torch' in Lua. So I am wondering how come you provided a model to be useful in Keras. please share the steps or code snippets on how you saved the weights of pre-trained nn4.small2.v1 in CSV and later loaded them in Keras. Thanks

**Comment by krasserm** [comment]
As mentioned in the article I used https://github.com/iwantooxxoox/Keras-OpenFace for that purpose. If this doesn't help, please re-open the ticket.

**Comment by jadhavsaurabh** [comment]
thank you for help sir @krasserm
