### ISSUE TITLE
Use of LinearSVM

### ISSUE THREAD

**Issue by PoonamZ** [krasserm/face-recognition#17]

**Comment by PoonamZ** [comment]
@krasserm In this Repository why we used the LinearSVM ? Why not multi class SVM ? Is any specific reason behind it ?

**Comment by krasserm** [comment]
Choice of kernel and binary/multi classification are distinct concepts. You can do multi-class classification with a linear SVM. Non-linear SVMs do not perform better compared to a linear SVM on this particular dataset because face clusters are linearly separable in embedding space.

**Comment by PoonamZ** [comment]
But how to find the probability values for recognized class using the LinearSVM ?

**Comment by krasserm** [comment]
Don't use class probabilities but rather Euclidean distance as a criterion for similarity. This is what the NN was trained for.

**Comment by PoonamZ** [comment]
OK thank you.
