### ISSUE TITLE
while running notebook getting error?

### ISSUE THREAD

**Issue by 008karan** [krasserm/face-recognition#2]
Getting an error while calculating embeddings.
`for i, m in enumerate(metadata):`
`----> 4     img = load_image(m.image_path())`
 `     5     img = align_image(img)`
  `    6     # scale RGB values to interval [0,1]`

`<ipython-input-14-23aefaa58a32> in load_image(path)`
  `   12     # in BGR order. So we need to reverse them`
    `---> 13    return img[...,::-1]`

`TypeError: 'NoneType' object is not subscriptable`

**Comment by krasserm** [comment]
I just ran the notebook again and cannot reproduce the error. Can you please provide more details such as:

- are you using the dataset provided by this repository or are you using your own dataset?
- current working directory
- ...

It looks like `cv2.imread` cannot read the from the given `path`. Does the path actually exist you're trying to load?
