### ISSUE TITLE
Am getting below error while running notebook

### ISSUE THREAD

**Issue by ajeyaraj03** [krasserm/face-recognition#26]
Face aligment section

RuntimeError                              Traceback (most recent call last)
<ipython-input-8-3a816f0216a4> in <module>
     14 
     15 # Initialize the OpenFace face alignment utility
---> 16 alignment = AlignDlib('models/landmarks.dat')
     17 
     18 # Load an image of Jacques Chirac

face-recognition/align.py in __init__(self, facePredictor)
     87 
     88         self.detector = dlib.get_frontal_face_detector()
---> 89         self.predictor = dlib.shape_predictor(facePredictor)
     90 
     91     def getAllFaceBoundingBoxes(self, rgbImg):

RuntimeError: Error deserializing a floating point number.
   while deserializing a dlib::matrix
   while deserializing object of type std::vector
   while deserializing object of type std::vector
   while deserializing object of type std::vector

i did install all requirements in virtual env.

**Comment by ajeyaraj03** [comment]
i used # Initialize the OpenFace face alignment utility
alignment = AlignDlib('models/shape_predictor_68_face_landmarks.dat')

68 shape predicter then started working thanks to 
https://medium.com/@lewisdgavin/facial-image-data-prep-for-a-deep-learning-model-fe547473a68b

**Comment by krasserm** [comment]
The `models/landmarks.dat` file is created by running the first cell in the notebook, I just verified that. So the change you made shouldn't be necessary. If you still think the first cell doesn't work correctly, please re-open the issue.
