### ISSUE TITLE
Double counting pairs in distance threshold calculation

### ISSUE THREAD

**Issue by alexaorrico** [krasserm/face-recognition#29]
In the file `face_recognition.ipynb` in the `Distance threshold` section, the creation of pairs for the f1 and accuracy calculations double count all embedding pairs and also include pairs of the same embeddings.

Instead of
```
for i in range(num - 1):
    for j in range(1, num):
```

it should be

```
for i in range(num - 1):
    for j in range(i + 1, num):
```

I would have liked to make a pull request myself, but cannot run the ipynb on my remote server to generate the new images required. Thank you!

**Comment by krasserm** [comment]
Good catch @alexaorrico, that's definitely a bug. Thanks for reporting, will fix it soon ...
