### ISSUE TITLE
Getting confidence level of test image

### ISSUE THREAD

**Issue by arevel190** [krasserm/face-recognition#3]
Hi,

First of all thank you for creating this project, it helped me a lot with understanding how the tech works.

I was wondering how could I get the confidence level when doing face recognition. I tried using the predict_proba() function on the KNN model but got an array where all values where zero except for one. I was looking for something like: [ 0.1 , 0.4 , 0.2 , 1.0 ] (Considering there are only 4 labels)

Thanks!

**Comment by yolob21** [comment]
This might be a little off topic, were you able to train the model using a triple loss function #1?

**Comment by krasserm** [comment]
@arevel190 

> I was wondering how could I get the confidence level when doing face recognition. I tried using the predict_proba() function on the KNN model but got an array where all values where zero except for one

This just means that the `k` nearest neighbors of a test example all belong to the same class. With the `knn` classifier from the notebook you won't see other results as it is configured with `k=1` (i.e. `n_neighbors=1`). 

Either use a larger number for `k` but a better idea is to make a radius search with the `knn.kneighbors()` method. The latter retrieves all neighbors within a given radius. From these you can compute the distribution over classes.

Hope that helps!

**Comment by arevel190** [comment]
@krasserm Thanks a lot for the suggestion :)
