### ISSUE TITLE
Accuracy on LFW

### ISSUE THREAD

**Issue by lukeb88** [krasserm/face-recognition#4]
In the article http://krasserm.github.io/2018/02/07/deep-face-recognition/ @krasserm said that the accuracy on LFW is 95.7%. 
But on the LFW official site (http://vis-www.cs.umass.edu/lfw/results.html#ImageRestrictedLF) is said that the accuracy with FaceNet is 0.9963%.
My question is: the difference between the two results could depend on the specific implementation of the Model, or it could depend on the fact that here we're testing on a small subset of the LFW?

**Comment by krasserm** [comment]
The model used in the blog post (nn4.small2) is a much smaller model than the top-performing model in the FaceNet paper. The [accuracy of nn4.small2 on the LFW benchmark](https://cmusatyalab.github.io/openface/models-and-accuracies/#accuracy-on-the-lfw-benchmark) is  93.0%. One reason for the difference to 95.7% is indeed the smaller LFW subset used in the blog post.

**Comment by lukeb88** [comment]
Thank you @krasserm! 
Apart from this clarification, your blog post helped me a lot.
