### ISSUE TITLE
Euclidean distance function

### ISSUE THREAD

**Issue by Fizmath** [krasserm/face-recognition#6]
Euclidean distance function:

def distance(emb1, emb2):
           return np.sum(np.square(emb1 - emb2))

should be 

def distance(emb1, emb2):
           return np.sqrt(np.sum((emb1 - emb2)**2))

**Comment by krasserm** [comment]
The text mentions a *squared L2 distance* so the implementation is according to that. Furthermore, if you only want to impose an ordering of neighbors it doesn't matter if you're using the squared L2 distance or L2 distance, and, since the squared L2 distance is faster to compute, it is preferred.
